# ============================================
# PetVetRAG 公共配置（所有环境共享）
# ============================================

# ============================================
# Nacos 配置
# ============================================
spring:
  cloud:
    nacos:
      discovery:
        server-addr: ${NACOS_SERVER_ADDR:127.0.0.1:8848}
        namespace: ${NACOS_NAMESPACE:public}
        group: DEFAULT_GROUP
        # 服务注册配置
        # 本地开发请显式绑定可达 IP，避免注册不可达的内网地址
        ip: ${NACOS_DISCOVERY_IP:127.0.0.1}
        # 注意：port 会自动使用 server.port 的值，无需手动配置
        # 健康检查配置
        heart-beat-interval: 5000  # 心跳间隔（毫秒）
        heart-beat-timeout: 15000  # 心跳超时（毫秒）
        ip-delete-timeout: 30000   # IP删除超时（毫秒）
      config:
        server-addr: ${NACOS_SERVER_ADDR:127.0.0.1:8848}
        namespace: ${NACOS_NAMESPACE:}
        group: DEFAULT_GROUP
        file-extension: yml
        shared-configs:
          - data-id: pet-vet-rag-common.yml
            group: DEFAULT_GROUP
            refresh: true
    # LoadBalancer 配置（用于 Feign 客户端服务发现）
    loadbalancer:
      cache:
        enabled: true
        ttl: 35s  # 服务实例缓存时间
        capacity: 256  # 缓存容量
    # OpenFeign 配置（Spring Cloud OpenFeign 2023.0.1）
    openfeign:
      client:
        config:
          # 默认配置（适用于所有 Feign 客户端）
          default:
            connect-timeout: 10000  # 连接超时时间（毫秒），10秒
            read-timeout: 300000    # 读取超时时间（毫秒），300秒（向量检索可能需要较长时间，特别是 Zilliz 连接时）
            logger-level: BASIC     # 日志级别：NONE, BASIC, HEADERS, FULL
          # pet-vet-embedding 服务特定配置
          # 注意：服务名称必须与 Nacos 中注册的服务名称一致
          # Nacos 中服务名称格式为 group@@serviceName，但 Feign 客户端只需使用 serviceName
          # LoadBalancer 会根据 Nacos discovery 配置的 group 自动解析
          pet-vet-embedding:
            connect-timeout: 10000  # 连接超时时间（毫秒），10秒
            read-timeout: 300000    # 读取超时时间（毫秒），300秒（向量检索可能需要较长时间，特别是 Zilliz 连接时）
            logger-level: FULL      # 日志级别：FULL（开发环境用于诊断，生产环境建议使用 BASIC）
      # 启用请求和响应压缩
      compression:
        request:
          enabled: true
          mime-types: application/json,application/xml,text/xml
          min-request-size: 2048
        response:
          enabled: true
  # AI 配置（所有环境公共）
  # 支持 OpenAI、DeepSeek 和 xAI Grok
  # 推荐使用 DeepSeek（价格更便宜，国内访问更稳定）或 Grok（性能优秀）
  ai:
    # AI 提供商类型：openai、deepseek 或 grok（默认使用 deepseek）
    provider:
      type: ${AI_PROVIDER_TYPE:deepseek}
    
    # OpenAI 配置
    openai:
      api-key: ${OPENAI_API_KEY:}
      chat:
        options:
          model: ${OPENAI_MODEL:gpt-4o}
          temperature: ${OPENAI_TEMPERATURE:0.7}
    
    # DeepSeek 配置（推荐）
    # DeepSeek 使用 OpenAI 兼容的 API，价格更便宜，国内访问更稳定
    # 申请地址：https://platform.deepseek.com/
    # ⚠️ 注意：API Key 必须通过环境变量 DEEPSEEK_API_KEY 配置，不要直接写在配置文件中
    deepseek:
      api-key: ${DEEPSEEK_API_KEY:}
      base-url: ${DEEPSEEK_BASE_URL:https://api.deepseek.com}
      chat:
        options:
          model: ${DEEPSEEK_MODEL:deepseek-chat}
          temperature: ${DEEPSEEK_TEMPERATURE:0.7}
    
    # xAI Grok 配置
    # Grok 是 xAI 开发的 AI 模型，使用 OpenAI 兼容的 API
    # 申请地址：https://x.ai/
    # ⚠️ 注意：API Key 必须通过环境变量 GROK_API_KEY 配置，不要直接写在配置文件中
    grok:
      api-key: ${GROK_API_KEY:}
      base-url: ${GROK_BASE_URL:https://api.x.ai/v1}
      chat:
        options:
          model: ${GROK_MODEL:grok-4-latest}
          temperature: ${GROK_TEMPERATURE:0.7}

# ============================================
# RAG 配置
# ============================================
rag:
  classifier:
    # 混合方案总开关
    hybrid:
      enabled: false  # 设置为 true 启用混合方案
    
    # 对比验证模式（同时运行新旧方案进行对比，用于验证）
    compare-mode: false  # 设置为 true 启用对比验证模式（需要 hybrid.enabled=true）
    
    # 缓存层配置
    cache:
      enabled: true
      max-size: 1000
      expire-minutes: 5
    
    # 规则层配置
    rule:
      enabled: true
    
    # 兜底策略配置
    fallback:
      enabled: true

  # 记忆管理配置
  memory:
    # 对话窗口大小（保留最近N轮对话，每轮包含USER和ASSISTANT两条消息）
    window-size: 10
    # Redis过期时间（天）
    ttl-days: 30
  
  # 检索配置
  retrieval:
    # 默认最大检索结果数
    default-max-results: 10
    # 默认最小相似度分数（0.0-1.0）
    default-min-score: 0.7
    # 默认上下文窗口大小（用于生成答案时包含的上下文chunk数量）
    default-context-window-size: 5
    # 检索质量阈值（低于此值，不使用检索结果）
    min-retrieval-score: 0.6
    # 强制使用知识库的关键词（如果查询包含这些词，必须检索）
    force-retrieval-keywords: "疾病,症状,诊断,治疗,疫苗,感染,炎症,手术,药物"
    # 跳过检索的关键词（如果查询包含这些词，不检索）
    skip-retrieval-keywords: "你好,谢谢,再见,哈哈"
    # 默认策略（true: 默认检索，false: 默认不检索）
    default-retrieval: true
  
  # 生成配置
  generation:
    # 是否默认启用生成
    default-enable-generation: true
    # 默认模型名称（openai, ollama等）
    default-model-name: gpt-3.5-turbo
    # 生成温度（0.0-2.0，越高越随机）
    temperature: 0.7
    # 最大token数
    max-tokens: 1000
    # 提示词模板
    prompt-template: |
      基于以下上下文信息回答用户的问题。如果上下文中没有相关信息，请说明无法从提供的信息中找到答案。
      
      上下文信息：
      {context}
      
      用户问题：{question}
      
      请提供详细、准确的答案：

# ============================================
# MyBatis-Plus 基础配置（所有环境公共）
# ============================================
mybatis-plus:
  mapper-locations: classpath*:/mapper/**/*.xml
  type-aliases-package: com.petvet.rag.app.domain
  configuration:
    map-underscore-to-camel-case: true

# ============================================
# 向量数据库配置（复用embedding模块的配置）
# ============================================
# 注意：RAG模块需要访问向量数据库，可以通过Feign调用embedding服务
# 或者直接配置向量数据库连接（如果需要在RAG模块中直接访问）
