# ============================================
# PetVetRAG 生产环境配置
# ============================================

# 数据源配置（生产环境）
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://${DB_HOST:prod-db}:${DB_PORT:3306}/${DB_NAME:pet_vet_rag}?useUnicode=true&characterEncoding=utf-8&useSSL=true&serverTimezone=Asia/Shanghai
    username: ${DB_USERNAME:}
    password: ${DB_PASSWORD:}
    hikari:
      maximum-pool-size: 20
      minimum-idle: 5
      connection-timeout: 30000
      idle-timeout: 600000
      max-lifetime: 1800000
  
  # Redis 配置（生产环境）
  data:
    redis:
      host: ${REDIS_HOST:prod-redis}
      port: ${REDIS_PORT:6379}
      password: ${REDIS_PASSWORD:}
      database: ${REDIS_DB:0}
      lettuce:
        pool:
          max-active: 20
          max-idle: 10
          min-idle: 5
          max-wait: -1ms
      timeout: 5000ms  # Redis 连接超时 5 秒

# MyBatis-Plus 配置（生产环境）
mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.slf4j.Slf4jImpl # 生产环境使用日志框架

# 生产环境特定配置
rag:
  retrieval:
    default-max-results: 10
    default-min-score: 0.7
  generation:
    default-enable-generation: true
    default-model-name: deepseek  # 生产环境使用 DeepSeek（推荐，价格更便宜）
    # 生产环境建议使用更稳定的模型
    temperature: 0.7
    max-tokens: 1500

# 日志配置（生产环境）
logging:
  level:
    root: INFO
    com.petvet.rag.app.mapper: INFO
    com.alibaba.nacos: WARN
    com.alibaba.cloud.nacos: WARN
