# ============================================
# PetVet Gateway 公共配置（所有环境共享）
# ============================================
# Data ID: pet-vet-gateway-common.yml
# Group: DEFAULT_GROUP
# Namespace: (空，使用 public 命名空间)
# 此文件用于上传到 Nacos 配置中心，包含所有环境的公共配置
# ============================================

# Spring Cloud Gateway 配置（所有环境公共）
spring:
  cloud:
    gateway:
      # 全局跨域配置
      globalcors:
        cors-configurations:
          '[/**]':
            allowed-origins: "*"
            allowed-methods: "*"
            allowed-headers: "*"
            allow-credentials: true
            max-age: 3600
      # 路由配置
      routes:
        # AI服务路由
        - id: pet-vet-ai-service
          uri: lb://pet-vet-ai-service
          predicates:
            - Path=/api/ai/**
          filters:
            - StripPrefix=1
        # 嵌入服务路由
        - id: pet-vet-embedding-service
          uri: lb://pet-vet-embedding-service
          predicates:
            - Path=/api/embedding/**
          filters:
            - StripPrefix=1
        # RAG服务路由
        - id: pet-vet-rag-service
          uri: lb://pet-vet-rag-service
          predicates:
            - Path=/api/rag/**
          filters:
            - StripPrefix=1
        # MCP服务路由
        - id: pet-vet-mcp-service
          uri: lb://pet-vet-mcp-service
          predicates:
            - Path=/api/mcp/**
          filters:
            - StripPrefix=1
    # Nacos 配置（所有环境公共）
    nacos:
      discovery:
        server-addr: ${NACOS_SERVER_ADDR:127.0.0.1:8848}
        namespace: ${NACOS_NAMESPACE:public}
        group: DEFAULT_GROUP
        # 服务注册配置
        # 本地开发请显式绑定可达 IP，避免注册不可达的内网地址
        ip: ${NACOS_DISCOVERY_IP:127.0.0.1}
        # 注意：port 会自动使用 server.port 的值，无需手动配置
        # 健康检查配置
        heart-beat-interval: 5000  # 心跳间隔（毫秒）
        heart-beat-timeout: 15000  # 心跳超时（毫秒）
        ip-delete-timeout: 30000   # IP删除超时（毫秒）
      config:
        server-addr: ${NACOS_SERVER_ADDR:127.0.0.1:8848}
        namespace: ${NACOS_NAMESPACE:}
        group: DEFAULT_GROUP
        file-extension: yml
        shared-configs:
          - data-id: pet-vet-gateway-common.yml
            group: DEFAULT_GROUP
            refresh: true
    # LoadBalancer 配置（用于服务发现）
    loadbalancer:
      cache:
        enabled: true
        ttl: 35s  # 服务实例缓存时间
        capacity: 256  # 缓存容量
    # Sentinel 配置（所有环境公共）
    sentinel:
      transport:
        dashboard: ${SENTINEL_DASHBOARD:localhost:8091}
        port: 8719
        # 连接超时时间（毫秒），默认 3 秒
        heartbeat-interval-ms: 5000
      # 设置为 false：延迟初始化，不阻塞应用启动；如果 Dashboard 不可用，只记录警告，不抛出异常
      eager: false
      web:
        filter:
          enabled: true
          url-patterns: /**
      compatibility-verifier:
        enabled: false
      # Sentinel 规则持久化到 Nacos
      # 所有规则都支持通过Nacos配置中心动态调整，无需重启应用
      datasource:
        # 网关流控规则（Gateway Flow Rules）
        # 作用：限制每个服务/API分组的QPS，防止服务过载
        # 配置路径：Nacos -> pet-vet-gateway-gw-flow-rules (SENTINEL_GROUP)
        # 数据格式：JSON数组
        # 示例：[{"resource":"pet-vet-ai-service","count":50,"intervalSec":1}]
        gw-flow:
          nacos:
            server-addr: ${NACOS_SERVER_ADDR:127.0.0.1:8848}
            namespace: ${NACOS_NAMESPACE:}
            data-id: ${spring.application.name}-gw-flow-rules
            group-id: SENTINEL_GROUP
            rule-type: gw-flow
        # 网关API分组（Gateway API Group）
        # 作用：将URL路径模式映射到API分组名称，便于流控规则引用
        # 配置路径：Nacos -> pet-vet-gateway-gw-api-group-rules (SENTINEL_GROUP)
        # 数据格式：JSON数组
        # 示例：[{"apiName":"ai-api","predicateItems":[{"pattern":"/api/ai/**","matchStrategy":1}]}]
        # 注意：此配置优先级高于代码中的默认配置
        gw-api-group:
          nacos:
            server-addr: ${NACOS_SERVER_ADDR:127.0.0.1:8848}
            namespace: ${NACOS_NAMESPACE:}
            data-id: ${spring.application.name}-gw-api-group-rules
            group-id: SENTINEL_GROUP
            rule-type: gw-api-group
        # 网关降级规则（Gateway Degrade Rules）
        # 作用：当服务响应时间过长或异常率过高时，自动熔断，防止故障扩散
        # 配置路径：Nacos -> pet-vet-gateway-gw-degrade-rules (SENTINEL_GROUP)
        # 数据格式：JSON数组
        # 示例：[{"resource":"pet-vet-ai-service","grade":0,"count":100,"timeWindow":10}]
        # grade: 0-慢调用比例, 1-异常比例, 2-异常数
        # count: 阈值（慢调用比例或异常比例，单位：%）
        # timeWindow: 熔断时长（秒）
        gw-degrade:
          nacos:
            server-addr: ${NACOS_SERVER_ADDR:127.0.0.1:8848}
            namespace: ${NACOS_NAMESPACE:}
            data-id: ${spring.application.name}-gw-degrade-rules
            group-id: SENTINEL_GROUP
            rule-type: gw-degrade
        # 系统保护规则（System Rules）
        # 作用：根据系统整体负载（CPU、内存、QPS等）自动触发保护
        # 配置路径：Nacos -> pet-vet-gateway-system-rules (SENTINEL_GROUP)
        # 数据格式：JSON数组
        # 示例：[{"avgRt":1000,"maxThread":10,"qps":1000,"highestSystemLoad":0.8}]
        # 注意：系统规则是全局的，不需要指定resource
        system:
          nacos:
            server-addr: ${NACOS_SERVER_ADDR:127.0.0.1:8848}
            namespace: ${NACOS_NAMESPACE:}
            data-id: ${spring.application.name}-system-rules
            group-id: SENTINEL_GROUP
            rule-type: system
        # 授权规则（Authority Rules）
        # 作用：通过黑白名单机制，控制特定来源对资源的访问权限
        # 配置路径：Nacos -> pet-vet-gateway-authority-rules (SENTINEL_GROUP)
        # 数据格式：JSON数组
        # 示例：[{"resource":"pet-vet-ai-service","limitApp":"app1,app2","strategy":0}]
        # strategy: 0-白名单, 1-黑名单
        # limitApp: 应用名称列表，多个用逗号分隔
        authority:
          nacos:
            server-addr: ${NACOS_SERVER_ADDR:127.0.0.1:8848}
            namespace: ${NACOS_NAMESPACE:}
            data-id: ${spring.application.name}-authority-rules
            group-id: SENTINEL_GROUP
            rule-type: authority
  # Redis 配置（所有环境公共，环境特定值在各环境配置文件中覆盖）
  data:
    redis:
      host: ${REDIS_HOST:localhost}
      port: ${REDIS_PORT:6379}
      password: ${REDIS_PASSWORD:}
      database: 0
      timeout: 3000ms
      lettuce:
        pool:
          max-active: 8
          max-idle: 8
          min-idle: 0

# Spring Boot Actuator 配置（所有环境公共）
management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,prometheus
  endpoint:
    health:
      show-details: always

# 网关配置（公共配置）
gateway:
  # 白名单配置（不需要鉴权的路径）
  whitelist:
    - /api/auth/**
    - /api/public/**
    - /actuator/**
    - /health
    - /favicon.ico
  # JWT配置（公共配置，环境特定值在各环境配置文件中覆盖）
  jwt:
    secret: ${JWT_SECRET:pet-vet-gateway-secret-key-change-in-production-environment-minimum-32-characters}
    expiration: ${JWT_EXPIRATION:604800000}
    header: Authorization
    prefix: Bearer 
  # 授权配置（公共配置，环境特定值在各环境配置文件中覆盖）
  auth:
    # 企业微信配置
    wework:
      enabled: ${WEWORK_ENABLED:true}
      corp-id: ${WEWORK_CORP_ID:}
      agent-id: ${WEWORK_AGENT_ID:}
      secret: ${WEWORK_SECRET:}
      redirect-uri: ${WEWORK_REDIRECT_URI:}
      urls:
        auth-url-template: ${WEWORK_AUTH_URL:https://open.work.weixin.qq.com/wwopen/sso/qrConnect?appid=%s&agentid=%s&redirect_uri=%s&state=%s}
        user-info-url-template: ${WEWORK_USER_INFO_URL:https://qyapi.weixin.qq.com/cgi-bin/user/getuserinfo?access_token=%s&code=%s}
        access-token-url-template: ${WEWORK_ACCESS_TOKEN_URL:https://qyapi.weixin.qq.com/cgi-bin/gettoken?corpid=%s&corpsecret=%s}
    # 微信配置
    wechat:
      enabled: ${WECHAT_ENABLED:true}
      app-id: ${WECHAT_APP_ID:}
      app-secret: ${WECHAT_APP_SECRET:}
      redirect-uri: ${WECHAT_REDIRECT_URI:}
      urls:
        auth-url-template: ${WECHAT_AUTH_URL:https://open.weixin.qq.com/connect/qrconnect?appid=%s&redirect_uri=%s&response_type=code&scope=snsapi_login&state=%s#wechat_redirect}
        access-token-url-template: ${WECHAT_ACCESS_TOKEN_URL:https://api.weixin.qq.com/sns/oauth2/access_token?appid=%s&secret=%s&code=%s&grant_type=authorization_code}
        user-info-url-template: ${WECHAT_USER_INFO_URL:https://api.weixin.qq.com/sns/userinfo?access_token=%s&openid=%s}
    # 支付宝配置
    alipay:
      enabled: ${ALIPAY_ENABLED:true}
      app-id: ${ALIPAY_APP_ID:}
      private-key: ${ALIPAY_PRIVATE_KEY:}
      public-key: ${ALIPAY_PUBLIC_KEY:}
      redirect-uri: ${ALIPAY_REDIRECT_URI:}
      urls:
        auth-url-template: ${ALIPAY_AUTH_URL:https://openauth.alipay.com/oauth2/publicAppAuthorize.htm?app_id=%s&scope=auth_user&redirect_uri=%s&state=%s}
        user-info-url-template: ${ALIPAY_USER_INFO_URL:https://openapi.alipay.com/gateway.do}
    # QQ配置
    qq:
      enabled: ${QQ_ENABLED:true}
      app-id: ${QQ_APP_ID:}
      app-key: ${QQ_APP_KEY:}
      redirect-uri: ${QQ_REDIRECT_URI:}
      urls:
        auth-url-template: ${QQ_AUTH_URL:https://graph.qq.com/oauth2.0/authorize?response_type=code&client_id=%s&redirect_uri=%s&state=%s&scope=get_user_info}
        access-token-url-template: ${QQ_ACCESS_TOKEN_URL:https://graph.qq.com/oauth2.0/token?grant_type=authorization_code&client_id=%s&client_secret=%s&code=%s&redirect_uri=%s}
        open-id-url-template: ${QQ_OPENID_URL:https://graph.qq.com/oauth2.0/me?access_token=%s}
        user-info-url-template: ${QQ_USER_INFO_URL:https://graph.qq.com/user/get_user_info?access_token=%s&oauth_consumer_key=%s&openid=%s}
  # 日志配置（公共配置，环境特定值在各环境配置文件中覆盖）
  log:
    enabled: ${LOG_ENABLED:true}
    request-body: ${LOG_REQUEST_BODY:true}
    response-body: ${LOG_RESPONSE_BODY:true}
    max-body-size: ${LOG_MAX_BODY_SIZE:10240}
  # Sentinel流控规则配置（支持动态调整）
  sentinel:
    flow-rule:
      # 默认时间窗口（秒），所有服务共享，除非服务单独指定
      interval-sec: ${SENTINEL_FLOW_RULE_INTERVAL_SEC:1}
      # AI服务流控规则
      ai-service:
        # QPS限制（每秒请求数）
        count: ${SENTINEL_AI_SERVICE_QPS:50}
        # 时间窗口（秒），如果未设置则使用上面的默认值
        interval-sec: ${SENTINEL_AI_SERVICE_INTERVAL_SEC:}
      # Embedding服务流控规则
      embedding-service:
        count: ${SENTINEL_EMBEDDING_SERVICE_QPS:50}
        interval-sec: ${SENTINEL_EMBEDDING_SERVICE_INTERVAL_SEC:}
      # RAG服务流控规则
      rag-service:
        count: ${SENTINEL_RAG_SERVICE_QPS:50}
        interval-sec: ${SENTINEL_RAG_SERVICE_INTERVAL_SEC:}
      # MCP服务流控规则
      mcp-service:
        count: ${SENTINEL_MCP_SERVICE_QPS:30}
        interval-sec: ${SENTINEL_MCP_SERVICE_INTERVAL_SEC:}
    # API分组配置（支持动态调整）
    # 注意：Nacos中的gw-api-group配置优先级更高，会覆盖这里的默认配置
    api-group:
      # AI服务API分组
      ai-api:
        # URL路径模式（支持通配符）
        pattern: ${SENTINEL_AI_API_PATTERN:/api/ai/**}
      # Embedding服务API分组
      embedding-api:
        pattern: ${SENTINEL_EMBEDDING_API_PATTERN:/api/embedding/**}
      # RAG服务API分组
      rag-api:
        pattern: ${SENTINEL_RAG_API_PATTERN:/api/rag/**}
      # MCP服务API分组
      mcp-api:
        pattern: ${SENTINEL_MCP_API_PATTERN:/api/mcp/**}

