# ============================================
# PetVet Embedding 服务 - 开发环境配置
# 配置文件名: pet-vet-embedding-dev.yml
# Group: DEFAULT_GROUP
# 说明: 开发环境特定配置
# ============================================

spring:
  config:
    # Spring Boot 3.x 需要显式导入 Nacos 配置
    import:
      - optional:nacos:pet-vet-embedding-common.yml?group=DEFAULT_GROUP
      - optional:nacos:pet-vet-embedding-dev.yml?group=DEFAULT_GROUP
  cloud:
    nacos:
      discovery:
        # Nacos 服务发现配置（必须保留，用于连接 Nacos）
        server-addr: ${NACOS_SERVER_ADDR:127.0.0.1:8848}
        namespace: ${NACOS_NAMESPACE:public}
        group: ${NACOS_GROUP:DEFAULT_GROUP}
        # 服务注册配置
        # 本地开发请显式绑定可达 IP，避免注册不可达的内网地址
        ip: ${NACOS_DISCOVERY_IP:127.0.0.1}
        # 注意：port 会自动使用 server.port 的值，无需手动配置
        # 健康检查配置
        heart-beat-interval: 5000  # 心跳间隔（毫秒）
        heart-beat-timeout: 15000  # 心跳超时（毫秒）
        ip-delete-timeout: 30000   # IP删除超时（毫秒）
  
  # 数据源配置（开发环境）
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://${DB_HOST:localhost}:${DB_PORT:3306}/${DB_NAME:pet_vet_embedding}?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=Asia/Shanghai&allowPublicKeyRetrieval=true
    username: ${DB_USERNAME:root}
    password: ${DB_PASSWORD:root12345678}
  
  # Redis 配置（开发环境）
  data:
    redis:
      host: ${REDIS_HOST:localhost}
      port: ${REDIS_PORT:6379}
      password: ${REDIS_PASSWORD:}
      database: ${REDIS_DB:0}
      lettuce:
        pool:
          max-active: 8
          max-idle: 8
          min-idle: 0
          max-wait: -1ms

# MyBatis-Plus 配置（开发环境）
mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl # 开发环境打印 SQL

logging:
  level:
    root: INFO
    com.petvet.embedding: DEBUG
    com.petvet.embedding.app.mapper: DEBUG
    dev.langchain4j: DEBUG

# ============================================
# 向量数据库配置 - 开发环境
# ============================================
vector:
  database:
    type: zilliz
    qdrant:
      host: https://e2b72e30-6371-4b2f-a925-af91477e9f25.europe-west3-0.gcp.cloud.qdrant.io
      port: 6334
      collection-name: pet-vet-embeddings-v2
    zilliz:
      host: https://in03-404be71e0f75d6e.serverless.aws-eu-central-1.cloud.zilliz.com
      port: 19530
      collection-name: pet_vet_embeddings

